export const IS_FIXED_HEADER = 'IS_FIXED_HEADER'

export const IS_SHOW_SEARCH_BAR = 'IS_SHOW_SEARCH_BAR'

export const IS_SHOW_MASK = 'IS_SHOW_MASK'

export const GET_SLIDERS = 'GET_SLIDERS'

export const GET_HOT_PRODUCTS = 'GET_HOT_PRODUCTS'

export const GET_HOT_SHOPS = 'GET_HOT_SHOPS'

export const GET_PRODUCTS = 'GET_PRODUCTS'

export const IS_SHOW_LOADING_TIPS = 'IS_SHOW_LOADING_TIPS'

export const IS_SHOW_LOADED_TIPS = 'IS_SHOW_LOADED_TIPS'


